# Generated by Django 6.0 on 2025-12-26 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("association", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "compulsory_for",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("compulsory", "Compulsory"),
                            ("optional", "Optional"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "association",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_items",
                        to="association.association",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_items",
                        to="association.session",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReceiverBankAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bank_name", models.CharField(max_length=100)),
                ("account_name", models.CharField(max_length=100)),
                ("account_number", models.CharField(max_length=20)),
                ("bank_code", models.CharField(blank=True, max_length=10, null=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "association",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bank_account",
                        to="association.association",
                    ),
                ),
            ],
        ),
    ]
