# Generated by Django 6.0 on 2025-12-26 09:42

import cloudinary.models
import utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Association",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "association_name",
                    models.CharField(default="other", max_length=255, unique=True),
                ),
                (
                    "association_short_name",
                    models.CharField(default="other", max_length=50, unique=True),
                ),
                (
                    "association_type",
                    models.CharField(
                        choices=[
                            ("hall", "Hall"),
                            ("department", "Department"),
                            ("faculty", "Faculty"),
                            ("other", "Other"),
                        ],
                        default="Other",
                        max_length=20,
                    ),
                ),
                ("theme_color", models.CharField(default="#9810fa", max_length=7)),
                (
                    "logo",
                    cloudinary.models.CloudinaryField(
                        default="DuesPay/default.jpg",
                        max_length=255,
                        validators=[utils.utils.validate_file_type],
                        verbose_name="image",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
