# Generated by Django 6.0 on 2025-12-26 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("association", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("100", "100 Level"),
                            ("200", "200 Level"),
                            ("300", "300 Level"),
                            ("400", "400 Level"),
                            ("500", "500 Level"),
                            ("600", "600 Level"),
                            ("All Levels", "All Levels"),
                        ],
                        default="100",
                        max_length=20,
                    ),
                ),
                ("phone_number", models.CharField(max_length=20)),
                ("matric_number", models.CharField(max_length=50)),
                ("faculty", models.CharField(blank=True, max_length=100, null=True)),
                ("department", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "association",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payers",
                        to="association.association",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payers",
                        to="association.session",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("session", "email"), name="unique_email_per_session"
                    ),
                    models.UniqueConstraint(
                        fields=("session", "phone_number"),
                        name="unique_phone_per_session",
                    ),
                    models.UniqueConstraint(
                        fields=("session", "matric_number"),
                        name="unique_matric_per_session",
                    ),
                ],
            },
        ),
    ]
